alter table public.recipes add column if not exists description text;

insert into public.recipes (title, time_min, meal_type, tags, description) values
  ('Homemade Energy Drink', 5, 'drink', '{"Drinks"}'::text[], 'This homemade energy drink uses natural ingredients to provide a clean energy boost without artificial additives or excess sugar.'),
  ('Almond Flour Shortbread with Lemon Glaze', 35, 'dessert', '{"Dessert"}'::text[], 'Delicate almond flour shortbread bars with vanilla and lemon zest, drizzled with a honey lemon glaze.'),
  ('Baked Stuffed Apples with Oat Crumble', 50, 'dessert', '{"Dessert"}'::text[], 'Whole apples cored and stuffed with a honey-oat, walnut, and date crumble, baked until tender.'),
  ('Dark Chocolate Bark with Nuts & Sea Salt', 20, 'dessert', '{"Dessert"}'::text[], 'Simple dark chocolate bark with honey, almonds, pistachios, and flaky sea salt.'),
  ('Coconut Flour Carrot Cake', 60, 'dessert', '{"Dessert"}'::text[], 'Moist coconut flour carrot cake with walnuts and a creamy honey-cream cheese frosting.'),
  ('Poached Figs with Honey & Ricotta', 25, 'dessert', '{"Dessert"}'::text[], 'Warm poached figs in a honey-vanilla syrup, served over creamy ricotta with toasted walnuts.'),
  ('Oat & Honey Tahini Cookies', 27, 'dessert', '{"Dessert"}'::text[], 'Chewy oat and tahini cookies sweetened with honey and flecked with dark chocolate or walnuts.'),
  ('Strawberry Coconut Ice Cream', 10, 'dessert', '{"Dessert"}'::text[], 'Creamy dairy-free strawberry ice cream made with frozen strawberries, coconut cream, and honey.'),
  ('Grilled Pineapple with Honey & Mint', 18, 'dessert', '{"Dessert"}'::text[], 'Caramelized grilled pineapple rings brushed with honey, coconut oil, lime, and fresh mint.'),
  ('Chocolate Coconut Truffles', 25, 'dessert', '{"Dessert"}'::text[], 'Decadent dark chocolate truffles made with coconut cream and honey, rolled in cacao and coconut.'),
  ('Almond Flour Lemon Cake', 50, 'dessert', '{"Dessert"}'::text[], 'Moist, fragrant lemon cake made with almond flour, Greek yogurt, and honey.'),
  ('Frozen Mango & Coconut Bark', 15, 'dessert', '{"Dessert"}'::text[], 'Refreshing frozen bark made with coconut cream, fresh mango, honey, lime zest, and toasted coconut.'),
  ('Oat Flour Apple Crumble', 55, 'dessert', '{"Dessert"}'::text[], 'Classic apple crumble with a honey-oat topping — warm, bubbly, and naturally sweetened.'),
  ('Date & Walnut Tart with Almond Crust', 55, 'dessert', '{"Dessert"}'::text[], 'Rustic tart with a honey-almond flour crust filled with Medjool dates, walnuts, and vanilla.'),
  ('Mango Coconut Panna Cotta', 25, 'dessert', '{"Dessert"}'::text[], 'Silky coconut milk panna cotta with fresh mango puree, honey, and a hint of vanilla.'),
  ('Baked Cinnamon Pears with Walnuts', 40, 'dessert', '{"Dessert"}'::text[], 'Warm baked pear halves glazed with honey, cinnamon, and coconut oil, topped with toasted walnuts.'),
  ('Banana Nice Cream', 10, 'dessert', '{"Dessert"}'::text[], 'Creamy dairy-free ice cream made from blended frozen bananas, coconut milk, and vanilla.'),
  ('Almond Flour Chocolate Chip Cookies', 22, 'dessert', '{"Dessert"}'::text[], 'Soft, chewy grain-free cookies made with almond flour, honey, coconut oil, and dark chocolate chips.'),
  ('Pear & Gorgonzola Bites with Honey, Walnuts & Arugula', 10, 'snack', '{"Snack"}'::text[], 'Ripe pear slices topped with Gorgonzola, walnuts, and honey, served on a bed of peppery arugula.'),
  ('Edamame with Sea Salt & Sesame', 15, 'snack', '{"Snack"}'::text[], 'Tender boiled edamame pods tossed in toasted sesame oil, sesame seeds, and flaky sea salt.'),
  ('Walnut & Date Energy Bites', 15, 'snack', '{"Snack"}'::text[], 'No-bake energy bites made with walnuts, Medjool dates, oats, and raw cacao powder.'),
  ('Caprese Skewers', 15, 'snack', '{"Snack"}'::text[], 'Simple bite-sized caprese skewers with cherry tomatoes, fresh mozzarella, basil, and balsamic glaze.'),
  ('Oat & Honey Granola Bars', 40, 'snack', '{"Snack"}'::text[], 'Chewy baked granola bars with rolled oats, pumpkin seeds, almond butter, honey, and dark chocolate.'),
  ('Celery with Almond Butter & Raisins', 10, 'snack', '{"Snack"}'::text[], 'Classic ants on a log — celery sticks filled with almond butter and topped with plump raisins.'),
  ('Mango & Chili Fruit Skewers', 15, 'snack', '{"Snack"}'::text[], 'Tropical mango, pineapple, and watermelon skewers tossed in a honey-lime chili dressing.'),
  ('Roasted Almonds with Rosemary & Sea Salt', 20, 'snack', '{"Snack"}'::text[], 'Oven-roasted whole almonds tossed with fresh rosemary, olive oil, and flaky sea salt.'),
  ('Coconut Flour Bliss Balls', 15, 'snack', '{"Snack"}'::text[], 'No-bake coconut flour energy balls with almond butter, honey, and dark chocolate chips.'),
  ('Hard-Boiled Eggs with Everything Seasoning', 22, 'snack', '{"Snack"}'::text[], 'Perfectly cooked hard-boiled eggs coated in a homemade everything bagel seasoning with olive oil.'),
  ('Apple Slices with Walnut Butter & Cinnamon', 10, 'snack', '{"Snack"}'::text[], 'Crisp apple wedges paired with a honey-cinnamon walnut butter dip.'),
  ('Cucumber Rounds with Smoked Salmon & Cream Cheese', 15, 'snack', '{"Snack"}'::text[], 'Crisp cucumber rounds topped with herbed cream cheese, smoked salmon, capers, and dill.'),
  ('Homemade Trail Mix', 20, 'snack', '{"Snack"}'::text[], 'Honey-roasted mixed nuts, seeds, coconut flakes, dried mango, and dark chocolate chips.'),
  ('Guacamole with Veggie Sticks', 15, 'snack', '{"Snack"}'::text[], 'Fresh chunky guacamole with lime and cilantro, served alongside crisp carrot, celery, and cucumber.'),
  ('Almond Butter & Banana Rice Cakes', 10, 'snack', '{"Snack"}'::text[], 'Brown rice cakes spread with honey-cinnamon almond butter and topped with banana slices.'),
  ('Quinoa Stuffed Portobello Mushrooms', 50, 'dinner', '{"Dinner"}'::text[], 'Large portobello caps stuffed with quinoa, spinach, sun-dried tomatoes, and goat cheese.'),
  ('Grass-Fed Beef Tacos with Cabbage Slaw', 30, 'dinner', '{"Dinner"}'::text[], 'Spiced grass-fed beef tacos in corn tortillas with crispy cabbage slaw and avocado.'),
  ('Baked Halibut with Mango Salsa', 30, 'dinner', '{"Dinner"}'::text[], 'Oven-baked halibut fillets topped with a vibrant fresh mango, jalapeño, and avocado salsa.'),
  ('Moroccan Chickpea Tagine', 60, 'dinner', '{"Dinner"}'::text[], 'Aromatic Moroccan-spiced tagine with sweet potato, chickpeas, dates, and cinnamon.'),
  ('Seared Duck Breast with Cherry Sauce', 35, 'dinner', '{"Dinner"}'::text[], 'Crispy-skinned duck breast served with a glossy balsamic cherry and honey pan sauce.'),
  ('Black Bean Enchiladas with Avocado Cream', 50, 'dinner', '{"Dinner"}'::text[], 'Spiced black bean corn tortilla enchiladas topped with melted cheddar and silky avocado cream.'),
  ('Pork Tenderloin with Apple & Fennel', 50, 'dinner', '{"Dinner"}'::text[], 'Seared pork tenderloin roasted over caramelized apples, fennel, and onion with a honey glaze.'),
  ('Baked Eggplant Parmesan', 60, 'dinner', '{"Dinner"}'::text[], 'Crispy almond flour–breaded eggplant layered with fresh mozzarella and homemade tomato sauce.'),
  ('Shrimp & Cauliflower Rice Stir Fry', 30, 'dinner', '{"Dinner"}'::text[], 'Healthy cauliflower fried rice with juicy shrimp, scrambled egg, peas, and coconut aminos.'),
  ('Roast Chicken with Root Vegetables', 95, 'dinner', '{"Dinner"}'::text[], 'Classic Sunday roast chicken with carrots, parsnips, and aromatic herbs in pan juices.'),
  ('Turkey & Vegetable Meatballs with Marinara', 50, 'dinner', '{"Dinner"}'::text[], 'Tender turkey meatballs packed with zucchini and carrot, simmered in a fresh herb marinara.'),
  ('Grilled Whole Sea Bass with Herbs', 35, 'dinner', '{"Dinner"}'::text[], 'Whole sea bass marinated in garlic, parsley, and lemon, then grilled to perfection.'),
  ('Mushroom & Lentil Bolognese over Zucchini Noodles', 55, 'dinner', '{"Dinner"}'::text[], 'Rich plant-based bolognese with brown lentils and cremini mushrooms over fresh zucchini noodles.'),
  ('Lamb Chops with Rosemary & Garlic', 25, 'dinner', '{"Dinner"}'::text[], 'Pan-seared lamb chops marinated in rosemary, garlic, lemon, and finished with butter.'),
  ('Baked Cod with Roasted Vegetables', 40, 'dinner', '{"Dinner"}'::text[], 'Flaky baked cod nestled among roasted zucchini, cherry tomatoes, olives, and capers.'),
  ('Coconut Curry Chicken', 45, 'dinner', '{"Dinner"}'::text[], 'Fragrant coconut milk curry with tender chicken thighs, tomatoes, and warming spices.'),
  ('Stuffed Acorn Squash with Wild Rice & Cranberries', 80, 'dinner', '{"Dinner"}'::text[], 'Roasted acorn squash halves filled with wild rice, dried cranberries, walnuts, and fresh herbs.'),
  ('Grass-Fed Beef & Vegetable Stir Fry', 25, 'dinner', '{"Dinner"}'::text[], 'Quick and flavorful stir fry with grass-fed beef, broccoli, snap peas, and coconut aminos sauce.'),
  ('Slow Cooker Chicken & Vegetable Stew', 380, 'dinner', '{"Dinner"}'::text[], 'Fall-off-the-bone slow cooker chicken thighs with root vegetables in a rich herb broth.'),
  ('Baked Lemon Herb Salmon', 25, 'dinner', '{"Dinner"}'::text[], 'Tender baked salmon fillets with garlic, fresh dill, lemon zest, and olive oil.'),
  ('Classic Nicoise Salad', 35, 'lunch', '{"Lunch"}'::text[], 'Traditional French Nicoise with green beans, potatoes, tuna, eggs, and olives in Dijon vinaigrette.'),
  ('Stuffed Bell Peppers with Quinoa & Black Beans', 55, 'lunch', '{"Lunch"}'::text[], 'Colorful bell peppers stuffed with spiced quinoa and black beans, topped with melted cheddar.'),
  ('Grilled Shrimp & Mango Salad', 23, 'lunch', '{"Lunch"}'::text[], 'Smoky grilled shrimp with fresh mango, avocado, cilantro, and a honey lime dressing.'),
  ('Spiced Carrot & Ginger Soup', 45, 'lunch', '{"Lunch"}'::text[], 'Velvety carrot soup with fresh ginger, cumin, coriander, and rich coconut milk.'),
  ('Caprese Salad with Heirloom Tomatoes', 15, 'lunch', '{"Lunch"}'::text[], 'Classic caprese with colorful heirloom tomatoes, fresh mozzarella, basil, and balsamic drizzle.'),
  ('Millet & Roasted Cauliflower Bowl', 50, 'lunch', '{"Lunch"}'::text[], 'Fluffy millet bowl with golden roasted cauliflower and chickpeas, drizzled with lemon tahini dressing.'),
  ('Egg Salad Lettuce Wraps', 25, 'lunch', '{"Lunch"}'::text[], 'Creamy egg salad with avocado, Dijon mustard, and dill, served in fresh butter lettuce cups.'),
  ('Warm Buckwheat Salad with Roasted Beets and Carrots', 55, 'lunch', '{"Lunch"}'::text[], 'Nutty warm buckwheat with caramelized roasted beets, carrots, toasted walnuts, and goat cheese.'),
  ('Cucumber & Smoked Salmon Rolls', 15, 'lunch', '{"Lunch"}'::text[], 'Elegant cucumber ribbon rolls filled with smoked salmon and herbed cream cheese.'),
  ('Miso Soup with Tofu & Seaweed', 25, 'lunch', '{"Lunch"}'::text[], 'Classic Japanese-inspired miso soup with silken tofu, wakame seaweed, and fresh ginger.'),
  ('Tuna Stuffed Avocado', 15, 'lunch', '{"Lunch"}'::text[], 'Creamy tuna salad made with olive oil-packed tuna, celery, and lemon, served in avocado halves.'),
  ('Brown Rice & Roasted Vegetable Bowl', 55, 'lunch', '{"Lunch"}'::text[], 'Nourishing brown rice bowl topped with caramelized roasted vegetables and creamy tahini dressing.'),
  ('Zucchini Noodles with Pesto & Cherry Tomatoes', 20, 'lunch', '{"Lunch"}'::text[], 'Light zucchini noodles tossed with homemade basil pesto and sautéed cherry tomatoes.'),
  ('Chickpea & Spinach Stew', 40, 'lunch', '{"Lunch"}'::text[], 'Hearty one-pot stew with chickpeas, wilted spinach, and warming spices in a tomato broth.'),
  ('Roasted Beet & Walnut Salad', 60, 'lunch', '{"Lunch"}'::text[], 'Earthy roasted beets over arugula with toasted walnuts, goat cheese, and balsamic honey dressing.'),
  ('Black Bean & Sweet Potato Tacos', 40, 'lunch', '{"Lunch"}'::text[], 'Smoky roasted sweet potato and spiced black bean tacos in corn tortillas with avocado and cilantro.'),
  ('Grilled Chicken & Avocado Salad', 27, 'lunch', '{"Lunch"}'::text[], 'Juicy grilled chicken over mixed greens with avocado, cherry tomatoes, and a lemon-honey dressing.'),
  ('Quinoa Tabbouleh', 30, 'lunch', '{"Lunch"}'::text[], 'Bright, herb-forward tabbouleh made with quinoa instead of bulgur, tossed in lemon-olive oil dressing.'),
  ('Brown Rice Congee with Soft Egg', 80, 'breakfast', '{"Breakfast"}'::text[], 'Warming brown rice porridge slow-cooked with ginger and topped with a soft egg and sesame oil.'),
  ('Oat Flour Blueberry Muffins', 37, 'breakfast', '{"Breakfast"}'::text[], 'Moist, fluffy blueberry muffins made with oat flour, honey, and full-fat yogurt.'),
  ('Tropical Smoothie Bowl', 10, 'breakfast', '{"Breakfast"}'::text[], 'Thick, vibrant smoothie bowl made with frozen mango and pineapple, topped with coconut and fresh fruit.'),
  ('Spinach & Feta Omelette', 12, 'breakfast', '{"Breakfast"}'::text[], 'Classic fluffy omelette filled with wilted spinach and crumbled feta cheese.'),
  ('Oat & Date Energy Bars', 35, 'breakfast', '{"Breakfast"}'::text[], 'Dense, chewy energy bars made with rolled oats, Medjool dates, and almond butter.'),
  ('Coconut Yogurt Parfait with Granola', 35, 'breakfast', '{"Breakfast"}'::text[], 'Layered coconut yogurt parfait with homemade honey-oat granola and fresh berries.'),
  ('Quinoa Breakfast Bowl with Poached Egg', 30, 'breakfast', '{"Breakfast"}'::text[], 'Savory quinoa bowl topped with a perfectly poached egg, avocado, and cherry tomatoes.'),
  ('Smoked Salmon & Avocado Bowl', 10, 'breakfast', '{"Breakfast"}'::text[], 'Fresh smoked salmon over creamy mashed avocado with cucumber, dill, and Greek yogurt.'),
  ('Veggie Egg Muffins', 35, 'breakfast', '{"Breakfast"}'::text[], 'Portable, protein-packed egg muffins loaded with bell pepper, spinach, and onion.'),
  ('Millet Porridge with Honey & Berries', 30, 'breakfast', '{"Breakfast"}'::text[], 'Creamy millet porridge sweetened with honey and topped with fresh mixed berries.'),
  ('Buckwheat Porridge with Dates & Walnuts', 25, 'breakfast', '{"Breakfast"}'::text[], 'Hearty, naturally sweet buckwheat porridge with Medjool dates, walnuts, and coconut milk.'),
  ('Avocado & Egg Stuffed Sweet Potato', 60, 'breakfast', '{"Breakfast"}'::text[], 'Roasted sweet potatoes stuffed with a baked egg and creamy mashed avocado.'),
  ('Overnight Oats with Chia & Mango', 10, 'breakfast', '{"Breakfast"}'::text[], 'Creamy make-ahead oats soaked overnight with chia seeds and topped with fresh mango.'),
  ('Coconut Flour Crepes', 25, 'breakfast', '{"Breakfast"}'::text[], 'Delicate grain-free crepes made with coconut flour, eggs, and coconut milk.'),
  ('Almond Flour Waffles', 25, 'breakfast', '{"Breakfast"}'::text[], 'Light, crispy grain-free waffles made with almond flour, eggs, and coconut oil.'),
  ('Baked Oatmeal with Berries', 45, 'breakfast', '{"Breakfast"}'::text[], 'Wholesome baked oatmeal packed with blueberries, honey, and warming cinnamon.'),
  ('Banana Oat Pancakes', 25, 'breakfast', '{"Breakfast"}'::text[], 'Fluffy, naturally sweetened pancakes made with blended oats and ripe bananas.'),
  ('Pop Tarts', 50, 'snack', '{"Snacks"}'::text[], 'A clean, grain-free take on the classic Pop Tart — coconut and almond flour crust, real strawberry jam filling, and a dark chocolate top. Childhood nostalgia, real food style.'),
  ('Blueberry Jam', 5, 'breakfast', '{"Breakfast"}'::text[], 'A 4-ingredient overnight jam that needs no cooking. Frozen blueberries, chia seeds, and lemon juice thicken into a spreadable, naturally sweet jam while you sleep.'),
  ('Homemade seasoned tortilla chips', 17, 'salty & crunchy', '{"Salty & Crunchy"}'::text[], 'This swap delivers the same bold flavor and satisfying crunch using real, whole ingredients.'),
  ('Speedy Chocolate Cake', 25, 'dessert', '{"Dessert"}'::text[], 'A cake you can make in a fry pan in 15 minutes with just 7 simple, real-food ingredients? Erm YES PLEASE!!! No oven needed — this protein-packed banana-chocolate cake comes together in one pan.'),
  ('Cheesy Almond Flour Crackers', 22, 'salty & crunchy', '{"Salty & Crunchy"}'::text[], 'These cheesy almond flour crackers deliver the same bold, savory crunch without the artificial flavorings and additives.'),
  ('Almond Flour Crusted Baked Chicken', 50, 'dinner', '{"Fast Food"}'::text[], 'Crispy, golden baked chicken with an almond flour crust — all the satisfying crunch of fried chicken without the seed oils or additives.'),
  ('Homemade Chocolate Date Bars', 10, 'dessert', '{"Sweet Treats"}'::text[], 'This swap mimics the rich chocolate, caramel, and peanut combination using only whole, nutrient-dense ingredients.'),
  ('Sweet Potato Fritters with Whipped Feta & Hot Honey', 30, 'breakfast', '{"Breakfast"}'::text[], 'Crispy sweet potato fritters stacked high with creamy whipped feta and a warm hot honey drizzle. Makes about 6 fritters / 2 servings.'),
  ('Chocolate Chia Pudding', 5, 'breakfast', '{"Breakfast"}'::text[], 'A high-fiber, no-cook dessert or breakfast that tastes like chocolate mousse. Five ingredients, five minutes of prep.'),
  ('Apple Cinnamon Overnight Oats', 5, 'breakfast', '{"Breakfast"}'::text[], 'Warm apple-pie flavors in a cold jar — diced apple, chia seeds, and cinnamon make this a satisfying no-cook breakfast.'),
  ('Raspberry Coconut Overnight Oats', 5, 'breakfast', '{"Breakfast"}'::text[], 'Creamy coconut milk oats with bursts of fresh raspberry and a sprinkle of shredded coconut — naturally sweet and ready in the morning.'),
  ('Chocolate Almond Overnight Oats', 5, 'breakfast', '{"Breakfast"}'::text[], 'Rich, chocolatey oats loaded with almond butter and cacao — prep takes 5 minutes the night before and breakfast is ready when you wake up.'),
  ('Lentil Tortilla Wraps', 13, 'lunch', '{"Lunch"}'::text[], 'A 5-ingredient wrap made entirely from red lentils — high protein, gluten-free, and way more satisfying than a flour tortilla. Mix the night before and cook in minutes.'),
  ('Chocolate Brownies', 45, 'dessert', '{"Dessert"}'::text[], 'Fudgy, nutrient-dense brownies made with sweet potato and cacao — naturally sweetened with honey and loaded with wholesome ingredients.'),
  ('Spiced Almond Flour Tortilla Chips', 22, 'salty & crunchy', '{"Salty & Crunchy"}'::text[], 'This swap delivers the same bold crunch and savory flavor without artificial additives or ultra-processed ingredients.'),
  ('Homemade Spiced Date Soda', 5, 'drink', '{"Drinks"}'::text[], 'This homemade soda mimics the unique spiced sweetness of Dr Pepper using natural ingredients like dates and spices, paired with sparkling water for fizz.'),
  ('Homemade Sparkling Spiced Date Soda', 5, 'drink', '{"Drinks"}'::text[], 'This swap delivers the same sweet, spiced, and fizzy satisfaction without the high-fructose corn syrup and artificial flavors.'),
  ('Grain-Free Veggie Lasagna', 40, 'dessert', '{"Baked Goods"}'::text[], 'This swap keeps the comforting layers but uses whole ingredients like zucchini slices instead of pasta and fresh herbs for flavor.'),
  ('Zucchini Lasagna with Almond Ricotta', 35, 'dessert', '{"Baked Goods"}'::text[], 'This swap delivers all the layers and comforting flavors of lasagna using zucchini and almond ricotta for a lighter, nutrient-packed alternative.'),
  ('Zucchini Lasagna with Fresh Tomato Sauce', 35, 'dessert', '{"Baked Goods"}'::text[], 'This swap replaces processed pasta and jarred sauce with fresh, nutrient-dense ingredients while still delivering the cheesy, saucy comfort of traditional lasagna.'),
  ('Cheesy Spiced Tortilla Chips', 15, 'snack', '{"Snacks"}'::text[], 'Satisfy your craving for cheesy, crunchy chips with a real food version made from whole ingredients.'),
  ('Homemade Spiced Tortilla Chips', 15, 'snack', '{"Snacks"}'::text[], 'This swap offers the same bold crunch and savory flavor without the artificial additives and ultra-processed ingredients.'),
  ('Spiced Almond Flour Crisps', 20, 'salty & crunchy', '{"Salty & Crunchy"}'::text[], 'These crisps deliver the same bold flavor and crunch using clean, whole ingredients.'),
  ('Sweet Potato Pizza Crust with Fresh Toppings', 35, 'dessert', '{"Baked Goods"}'::text[], 'This swap satisfies the craving for pizza with a nutrient-packed sweet potato crust and fresh, whole toppings.'),
  ('Date Caramel Bars', 20, 'dessert', '{"Sweet Treats"}'::text[], 'This swap delivers the same gooey caramel, crunchy base, and chocolatey topping with simple whole ingredients.'),
  ('Chocolate Date Caramel Bars', 20, 'dessert', '{"Sweet Treats"}'::text[], 'This swap satisfies the craving for chocolate and caramel with just five whole-food ingredients.'),
  ('Homemade Chocolate Caramel Bars', 20, 'dessert', '{"Sweet Treats"}'::text[], 'This swap delivers the same chocolatey, caramel, and cookie experience with whole, recognizable ingredients.'),
  ('Chocolate Date Nougat Bars', 10, 'dessert', '{"Sweet Treats"}'::text[], 'These Chocolate Date Nougat Bars replicate the fluffy, chocolate-coated nougat texture of 3 Musketeers using wholesome, real ingredients.'),
  ('Homemade Nut & Date Bar', 10, 'snack', '{"Snacks"}'::text[], 'This swap uses whole nuts and dates to create a chewy, satisfying snack without added sugars or preservatives.'),
  ('Sweet Potato Chips', 55, 'snack', '{"Snacks"}'::text[], 'Crispy oven-baked sweet potato chips seasoned with olive oil, salt, and pepper — naturally sweet, wholesome, and totally satisfying. Purple sweet potatoes work great too.'),
  ('Potato Chips', 55, 'snack', '{"Snacks"}'::text[], 'Real homemade potato chips baked (not fried) with just olive oil and salt — the satisfying crunch you love, made clean.'),
  ('Carrot Chips', 40, 'snack', '{"Snacks"}'::text[], 'Lightly spiced carrot chips baked with paprika and olive oil — naturally sweet, crispy, and packed with beta-carotene.'),
  ('Beet Chips', 40, 'snack', '{"Snacks"}'::text[], 'Vibrant, earthy beet chips baked to a satisfying crisp with just olive oil and salt — beautiful color, real nutrition.'),
  ('Kale Chips', 20, 'snack', '{"Snacks"}'::text[], 'Crispy, savory kale chips baked with just olive oil and salt — the ultimate nutrient-dense snack in under 15 minutes.'),
  ('Apple Cinnamon Chips', 130, 'snack', '{"Snacks"}'::text[], 'Naturally sweet apple slices dusted with cinnamon and slow-baked until perfectly crisp — no sugar, no oil, just real food.'),
  ('Zucchini Chips', 45, 'snack', '{"Snacks"}'::text[], 'Thin, crispy zucchini chips baked with olive oil, salt, and pepper — a light, satisfying snack with zero processed ingredients.'),
  ('Homemade Sweet Potato Chips', 30, 'salty & crunchy', '{"Salty & Crunchy"}'::text[], 'Crispy, salty, and satisfying—these homemade sweet potato chips are a healthier alternative without the additives.'),
  ('Homemade Crispy Tortilla Chips', 17, 'salty & crunchy', '{"Salty & Crunchy"}'::text[], 'This swap delivers the same bold crunch and zesty flavor using simple, whole ingredients you can pronounce.'),
  ('Homemade Chocolate Sandwich Cookies', 20, 'dessert', '{"Sweet Treats"}'::text[], 'This swap uses simple whole ingredients to recreate the chewy chocolate cookie sandwich you love, without any processed fillers.'),
  ('Quick Homemade Ramen', 15, 'fast food', '{"Fast Food"}'::text[], 'This swap delivers the same cozy noodle experience without the preservatives, MSG, and artificial flavors found in instant ramen.'),
  ('Crispy Baked Sweet Potato Chips', 35, 'salty & crunchy', '{"Salty & Crunchy"}'::text[], 'These sweet potato chips are oven-baked and satisfy the same salty, crunchy craving without the excess oil and preservatives.'),
  ('Cookie Pie', 20, 'dessert', '{"Dessert"}'::text[], 'A giant, fudgy almond butter cookie baked in a pie dish — crisp on the edges, soft and gooey in the center. Naturally sweetened with honey, grain-free, and incredibly easy to make.'),
  ('Healthy Almond Snickers', 15, 'dessert', '{"Dessert"}'::text[], 'A no-bake, date-sweetened take on the classic Snickers bar — layered with a chewy almond nougat base, creamy peanut caramel, crunchy roasted almonds, and a silky dark chocolate coating. Sweet, salty, creamy, and crunchy all in one bite.'),
  ('Simple Cookies', 18, 'dessert', '{"Dessert"}'::text[], 'Soft, chewy cookies made from just dates, oats, and hemp milk — no sugar, no butter, no fuss. Naturally sweetened and ready in 15 minutes.'),
  ('Chickpea Brownies', 30, 'dessert', '{"Dessert"}'::text[], 'Fudgy, flourless brownies made from blended chickpeas — packed with plant-based protein and naturally sweetened with raw honey. Ready in under 30 minutes.'),
  ('High Protein Dairy Free Cheesecake', 55, 'dessert', '{"Dessert"}'::text[], 'A creamy, protein-packed cheesecake made with chickpeas, cashews, and tofu — completely dairy-free and naturally sweetened with dates. Rich and satisfying with no compromise.'),
  ('4 Ingredient Flax and Pumpkin Seed Bread', 80, 'side', '{"Sides"}'::text[], 'A dense, hearty seed bread made with just four real ingredients — no flour, no yeast, no sugar. Naturally grain-free, high in fiber, and perfect toasted.'),
  ('Sweet Potato Brownie', 28, 'dessert', '{"Dessert"}'::text[], 'A flourless, fudgy brownie made from a single sweet potato. Dense and chocolatey with zero refined sugar — naturally sweetened with raw honey.'),
  ('No Bake Chocolate Cake', 20, 'dessert', '{"Dessert"}'::text[], 'A dense, smooth, and fudgy chocolate cake made with hard-boiled eggs and 100% dark chocolate — no oven needed. Rich, satisfying, and secretly packed with protein.'),
  ('Zucchini Roll-Up Enchiladas', 30, 'dinner', '{"Baked Goods"}'::text[], 'This veggie-packed version satisfies your craving for cheesy, saucy enchiladas without the processed tortillas or heavy fillers.'),
  ('Zucchini Lasagna with Fresh Ricotta', 40, 'dinner', '{"Baked Goods"}'::text[], 'This swap uses zucchini instead of pasta and fresh ricotta for a wholesome, comforting meal without the ultra-processed fillers.'),
  ('Zucchini Lasagna', 40, 'dinner', '{"Baked Goods"}'::text[], 'This swap replaces processed pasta with fresh zucchini for a nutrient-packed, wholesome alternative.'),
  ('Zucchini Chocolate Mousse', 20, 'dessert', '{"Dessert"}'::text[], 'A rich, creamy chocolate mousse made with just two ingredients — steamed zucchini and 100% dark chocolate. The hot zucchini melts the chocolate as it blends, creating a silky mousse that sets beautifully in the fridge. No one will guess the secret ingredient.'),
  ('Vegan Cashew Vanilla Icing', 10, 'dessert', '{"Dessert"}'::text[], 'Silky, dairy-free icing made from soaked raw cashews, raw honey, hemp milk, and vanilla. Creamy enough to frost a cake, clean enough to eat with a spoon. Credit: Jessica Laroche.'),
  ('Sweet Potato Salad', 45, 'lunch', '{"Salad"}'::text[], 'Roasted sweet potatoes over a bed of peppery arugula with creamy tahini dressing, feta, sliced avocado, and toasted pepitas. Simple, satisfying, and stunning on a platter.'),
  ('Sweet Potato Pizza Crust', 35, 'dinner', '{"Pizza"}'::text[], 'A 3-ingredient grain-free pizza crust made with mashed sweet potato and almond flour. No yeast, no rising, no fuss — just mix, flatten, and bake.'),
  ('Sweet Potato Hash & Eggs', 30, 'breakfast', '{"Breakfast"}'::text[], 'A one-skillet breakfast with tender sweet potato, poblano, kale, and eggs baked right into the hash. Ready in 30 minutes with real, whole-food ingredients.'),
  ('Sweet 4-Nut Granola', 42, 'breakfast', '{"Breakfast"}'::text[], 'A seriously loaded granola with four types of nuts, pumpkin seeds, almond butter, and raw honey. Crispier when spread thin across two baking sheets.'),
  ('Stovetop Popped Popcorn', 10, 'snack', '{"Snacks"}'::text[], 'This swap uses whole popcorn kernels and olive oil for a clean, crunchy snack without artificial additives.'),
  ('Spicy 4-Nut Granola', 42, 'snack', '{"Granola"}'::text[], 'All the crunch of the sweet version with a cayenne kick. Adjust the heat to your liking — bold and addictive.'),
  ('Sparkling Lemon Water', 3, 'drink', '{"Beverages"}'::text[], 'This swap satisfies the desire for something bubbly and flavorful without the artificial sweeteners found in diet soda.'),
  ('Simple Real Banana Bread', 55, 'breakfast', '{"Baked Goods"}'::text[], 'This simple banana bread uses whole, recognizable ingredients to deliver the same moist, sweet satisfaction without refined sugars or processed oils.'),
  ('Roasted Tomato Soup (also doubles as Marinara Sauce)', 50, 'dinner', '{"Soup"}'::text[], 'A dead-simple roasted tomato soup that also works beautifully as a marinara sauce. Just toss everything on a baking sheet, roast, and blend.'),
  ('Roasted Red Pepper & Spinach Frittata', 30, 'breakfast', '{"Breakfast"}'::text[], 'A vibrant, oven-finished frittata with roasted red peppers, wilted spinach, and crumbled feta. One skillet, 30 minutes, real ingredients.'),
  ('Real Food Tiramisu', 10, 'dessert', '{"Dessert"}'::text[], 'A no-bake, plant-based twist on tiramisu made with overnight oats, hemp milk, and mashed banana. Rich, creamy, and genuinely good for you.'),
  ('Real Food Pie Crust', 10, 'dessert', '{"Dessert"}'::text[], 'A two-ingredient no-bake pie crust made from dates and pecans. Press it into any pie pan and fill with your favorite real food filling — cheesecake, pecan pie, or anything else. No flour, no butter, no refined sugar.'),
  ('Real Food Pecan Pie', 60, 'dessert', '{"Dessert"}'::text[], 'A date-and-pecan crust filled with whole pecans, eggs, honey, and coconut oil. No corn syrup, no refined sugar — just pure, rich, real-food pecan pie. Add dark chocolate for an irresistible twist.'),
  ('Real Food Egg McMuffin', 10, 'breakfast', '{"Breakfast"}'::text[], 'A grain-free, whole-food take on the classic breakfast sandwich. Built on a 90 Second Bread English muffin and stacked with eggs, meat, and your favorite toppings.'),
  ('Real Food Cheesecake', 30, 'dessert', '{"Dessert"}'::text[], 'A shockingly simple two-ingredient cheesecake filling — just Greek yogurt and egg. Use our Real Food Pie Crust as the base, add honey for sweetness, and top with fresh fruit. Clean, creamy, and actually good for you.'),
  ('Real Food "Nutella" (Hazelnut)', 20, 'snack', '{"Sweet Treats"}'::text[], 'This DIY version satisfies your sweet tooth with the same creamy, chocolate-hazelnut flavor using just whole, clean ingredients.'),
  ('Real Food "Nutella" (Hazelnut Free)', 5, 'dessert', '{"Dessert"}'::text[], 'A two-minute chocolate spread made with raw cacao powder, honey, and hemp seeds — no hazelnuts, no refined sugar, no palm oil. Spread it on anything and feel zero guilt.'),
  ('Raw Dairy Honey Ice Cream', 10, 'dessert', '{"Dessert"}'::text[], 'Three-ingredient ice cream that''s impossibly creamy.'),
  ('Raw Chocolate Mousse', 10, 'dessert', '{"Dessert"}'::text[], 'A three-ingredient mousse that tastes indulgent but is completely clean. Avocado and banana blend into a silky base, then raw cacao powder turns it into a rich chocolate dream. Chill it and it sets like a real mousse.'),
  ('Perfect Sunny Side Up Eggs', 10, 'breakfast', '{"Breakfast"}'::text[], 'The easiest oven-baked sunny side up eggs with perfectly set whites and gloriously runny yolks. A drizzle of olive oil, salt, and red pepper flakes — that''s all you need for a protein-packed real food breakfast.'),
  ('Overnight Chia Pudding Bowl', 10, 'breakfast', '{"Breakfast"}'::text[], 'A hearty overnight bowl packed with oats, hemp seeds, fresh fruit, and pumpkin seeds — all softened in coconut water while you sleep. Zero cooking required.'),
  ('No-Bake Greek Yogurt Cheesecake', 10, 'dessert', '{"Sweet Treats"}'::text[], 'This swap captures the creamy, indulgent texture of cheesecake using Greek yogurt and a nut-based crust, without the processed sugars or additives.'),
  ('Medjool Date Cookies', 22, 'dessert', '{"Dessert"}'::text[], 'Soft, chewy cookies sweetened entirely by medjool dates — no refined sugar, just oats, oat flour, and the natural caramel richness of dates. Add chocolate chips to make them even better.'),
  ('Mediterranean Lentil Soup', 40, 'dinner', '{"Soup"}'::text[], 'A hearty, plant-powered soup with lentils, potatoes, and spinach in a rich tomato broth. Ready in 40 minutes and full of flavor.'),
  ('Lemon Zucchini Bread', 50, 'snack', '{"Bread"}'::text[], 'A bright, moist zucchini bread sweetened with raw honey and brightened with fresh lemon. Made with oat, coconut, or almond flour — no refined sugar, no seed oils.'),
  ('Lemon Bars', 30, 'dessert', '{"Dessert"}'::text[], 'Bright, zesty lemon bars with a simple almond flour crust and a honey-sweetened lemon filling. Top with fresh berries and optional shaved coconut.'),
  ('Kalamata Olive Hummus', 5, 'snack', '{"Dip"}'::text[], 'Creamy, blender hummus with chickpeas, tahini, lemon, and Kalamata olives. No preservatives, no mystery ingredients — just real food.'),
  ('Homemade Pistachio Milk', 2, 'drink', '{"Beverages"}'::text[], 'Naturally green-tinted and slightly sweet, pistachio milk is rich and creamy with a distinct nutty flavor. A beautiful, nutrient-dense alternative.'),
  ('Homemade Oat Milk', 2, 'drink', '{"Beverages"}'::text[], 'Creamy, slightly sweet, and perfect for coffee or cereal. Made with just oats and water — the most economical plant milk you can make at home.'),
  ('Homemade Nutty Date Bars', 10, 'dessert', '{"Sweet Treats"}'::text[], 'This swap combines dates, nuts, and 100% cacao for a naturally sweet, chewy, and satisfying alternative to Snickers.'),
  ('Homemade Italian Sausage Spiced Ground Meat', 15, 'dinner', '{"Fast Food"}'::text[], 'This swap captures the bold, herby flavors of Italian sausage without the preservatives and additives often found in store-bought versions.'),
  ('Homemade Italian Sausage Patties', 15, 'dinner', '{"Fast Food"}'::text[], 'This swap delivers the same bold Italian flavors using simple, whole ingredients without additives or preservatives.'),
  ('Homemade Honey Vanilla Marshmallow Alternative', 9, 'dessert', '{"Sweet Treats"}'::text[], 'This swap delivers the same fluffy, chewy texture using just four whole ingredients without corn syrup or additives.'),
  ('Homemade Hemp Milk', 2, 'drink', '{"Beverages"}'::text[], 'The easiest plant milk you can make — no soaking, no straining. Just hemp seeds, water, and an optional medjool date or two for natural sweetness. Ready in under a minute.'),
  ('Homemade Fruit Gummies', 7, 'snack', '{"Sweet Treats"}'::text[], 'These homemade fruit gummies use real fruit and gelatin for a chewy, naturally sweet treat without the artificial colors and sugar overload.'),
  ('Homemade Date Caramel Chocolate Bars', 20, 'dessert', '{"Sweet Treats"}'::text[], 'This swap gives you the same caramel-chocolate-cookie crunch without the ultra-processed ingredients.'),
  ('Homemade Crispy Puffed Rice Bars', 5, 'dessert', '{"Sweet Treats"}'::text[], 'This swap replicates the crispy texture and sweet flavor using whole ingredients and skips the marshmallows and processed additives.'),
  ('Homemade Chocolate Nut Bars', 10, 'dessert', '{"Sweet Treats"}'::text[], 'This swap combines the rich chocolate, caramel-like sweetness, and crunchy nuts you love in a Snickers without the ultra-processed ingredients.'),
  ('Homemade Beef Jerky', 250, 'snack', '{"Snacks"}'::text[], 'This simple homemade beef jerky uses just a few whole ingredients for a protein-packed snack without the added sugars, preservatives, or artificial flavorings found in store-bought versions.'),
  ('Homemade Almond Milk', 2, 'drink', '{"Beverages"}'::text[], 'Fresh almond milk with a clean, light flavor. Soak almonds overnight to bring out their natural creaminess — add a medjool date for a touch of sweetness.'),
  ('Ginger Dates', 15, 'dessert', '{"Dessert"}'::text[], 'Medjool dates stuffed with fresh ginger and coated in 100% dark chocolate. A warming, spicy-sweet bite with just three real ingredients — and optional sea salt for the finishing touch.'),
  ('Electrolyte Coconut Water', 5, 'drink', '{"Beverages"}'::text[], 'Natural sports drink replacement.'),
  ('Divine & Disappearing Cookies', 30, 'dessert', '{"Dessert"}'::text[], 'No refined sugar, no butter, no flour — just walnuts, Medjool dates, and a handful of pantry staples. Firm up in the fridge and disappear fast. Double the recipe.'),
  ('Dark Chocolate Date Bites', 15, 'dessert', '{"Dessert"}'::text[], 'A sweet treat with only three real ingredients. Medjool dates stuffed with almond butter, coated in dark chocolate, and finished with a pinch of sea salt.'),
  ('Crispy Roasted Chickpeas', 35, 'snack', '{"Snacks"}'::text[], 'Roasted chickpeas are a simple, whole-food alternative with a satisfying crunch and customizable seasoning.'),
  ('Crispy Potatoes', 35, 'side', '{"Sides"}'::text[], 'Baby potatoes baked cut-side down on a garlic-herb Parmesan paste — they come out golden, crispy, and impossible to stop eating.'),
  ('Crispy Baked Potato Slices', 30, 'side', '{"Salty & Crunchy"}'::text[], 'These baked potato slices deliver the same salty crunch with just three whole ingredients.'),
  ('Coconut Whipped Cream', 5, 'dessert', '{"Dessert"}'::text[], 'Three ingredients, five minutes. Full-fat coconut milk chilled until firm, then whipped with raw honey and vanilla into a cloud-like dairy-free topping.'),
  ('Citrus Honey Sparkler', 3, 'drink', '{"Beverages"}'::text[], 'This swap delivers the same fizzy, refreshing experience but uses natural flavors and a touch of unprocessed sweetness.'),
  ('Chickpea Salad Bowl', 25, 'lunch', '{"Salad"}'::text[], 'A hearty, Mediterranean-inspired bowl built on a pulse of chickpeas, tahini, and capers — layered over greens with blanched green beans, Kalamata olives, avocado, and fresh basil.'),
  ('Blender Banana Bread', 45, 'dessert', '{"Dessert"}'::text[], 'No flour, no refined sugar, no mixer needed. Just 5 real ingredients blended in a NutriBullet and baked in a pie dish. Done in 45 minutes.'),
  ('Birthday Cake Cookies', 25, 'dessert', '{"Dessert"}'::text[], 'Light, fluffy cookies made with just egg whites, applesauce, and coconut flour — studded with raspberries and ready in 15 minutes. All the fun of birthday cake without any of the junk. Makes 5 cookies.'),
  ('Best Buddha Bowl', 35, 'lunch', '{"Bowl"}'::text[], 'A fully loaded bowl with roasted sweet potato, massaged kale, fermented veggies, brown rice or quinoa, and a golden Turmeric Tahini Sauce. Colorful, nourishing, and completely real food.'),
  ('Bean & Artichoke Pasta Bowl', 17, 'lunch', '{"Pasta"}'::text[], 'A pantry-staple pasta bowl that comes together in 15 minutes. Grain-free pasta options, black beans, artichoke hearts, and olive oil — season to taste and adjust ratios as you like.'),
  ('Banana & Chickpea Pancakes', 15, 'breakfast', '{"Breakfast"}'::text[], 'Fluffy, naturally sweetened pancakes made with bananas, chickpeas, and eggs — no flour, no refined sugar. Ready in under 15 minutes.'),
  ('Avocado Chocolate Pudding', 5, 'dessert', '{"Sweet Treats"}'::text[], 'This swap delivers the same creamy, chocolatey satisfaction while using whole, nutrient-dense ingredients.'),
  ('90 Second Bread (English Muffin)', 4, 'snack', '{"Bread"}'::text[], 'A quick, grain-free bread made with just flaxseed and an egg — ready in 90 seconds flat. Perfect for a low-carb snack or sandwich swap.')

on conflict ((lower(title))) do update set
  time_min    = excluded.time_min,
  meal_type   = excluded.meal_type,
  tags        = excluded.tags,
  description = excluded.description,
  updated_at  = now();
